services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    depends_on:
      - llm_service

  llm_service:
    build: ./llm_service
    env_file:
      - ./llm_service/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend
