name: Build and Deploy Dockerized Multi-Service App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/${{ github.repository }}/backend
  IMAGE_LLM: ghcr.io/${{ github.repository }}/llm_service
  IMAGE_FRONTEND: ghcr.io/${{ github.repository }}/frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t $IMAGE_BACKEND:latest ./backend
          docker push $IMAGE_BACKEND:latest

      - name: Build and push llm_service image
        run: |
          docker build -t $IMAGE_LLM:latest ./llm_service
          docker push $IMAGE_LLM:latest

      - name: Build and push frontend image
        run: |
          docker build \
            --build-arg VITE_BACKEND_URL="omani-mental-health-bvgsffbacsf2hnbg.canadacentral-01.azurewebsites.net" \
            -t $IMAGE_FRONTEND:latest \
            ./frontend
          docker push $IMAGE_FRONTEND:latest

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy backend container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omani-mental-health'
          images: ${{ env.IMAGE_BACKEND }}:latest

      - name: Configure Backend Environment Variables
        run: |
          az webapp config appsettings set \
            --name 'omani-mental-health' \
            --resource-group $(az webapp show --name 'omani-mental-health' --query resourceGroup -o tsv) \
            --settings \
            LLM_SERVICE_URL="https://omani-mental-health-llm.azurewebsites.net/llm-chat" \
            AZURE_SPEECH_KEY="${{ secrets.AZURE_SPEECH_KEY }}" \
            AZURE_SPEECH_REGION="${{ secrets.AZURE_SPEECH_REGION }}"

  deploy-llm:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy llm_service container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omani-mental-health-llm'
          images: ${{ env.IMAGE_LLM }}:latest

      - name: Configure LLM Environment Variables
        run: |
          az webapp config appsettings set \
            --name 'omani-mental-health-llm' \
            --resource-group $(az webapp show --name 'omani-mental-health-llm' --query resourceGroup -o tsv) \
            --settings \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy frontend container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omani-mental-health-frontend'
          images: ${{ env.IMAGE_FRONTEND }}:latest
